-- IdolCal 初始 Schema（H2 开发/测试 与 PostgreSQL 生产 通用）
-- 命名与实体契约一致：camelCase -> snake_case；时间一律 BIGINT（UTC epoch millis）
-- ID 用 SQL 标准 GENERATED BY DEFAULT AS IDENTITY（H2 2.x / PostgreSQL 10+ 均支持，JPA IDENTITY 生成器兼容）
-- JSON 文本列用 TEXT：PostgreSQL 原生 TEXT；H2 2.x 中 TEXT 为 CHARACTER VARYING（无长度限制），读写兼容
-- 全部 IF NOT EXISTS + baseline-version=0：存量库（ddl-auto 时代建的表）自动跳过已有对象、补建缺失对象；
-- 全新库（测试内存库 / 生产 PostgreSQL）正常创建全部对象。唯一约束独立建索引（存量库表已存在时约束不会补进表）

-- 活动（events）
CREATE TABLE IF NOT EXISTS events (
    id             VARCHAR(32)  PRIMARY KEY,
    artist         VARCHAR(32)  NOT NULL,
    date           VARCHAR(10)  NOT NULL,
    end_date       VARCHAR(10),
    time           VARCHAR(5),
    timezone       VARCHAR(8),
    start_at_utc   BIGINT,
    title_en       VARCHAR(200) NOT NULL,
    title_zh       VARCHAR(200) NOT NULL,
    title_ko       VARCHAR(200) NOT NULL,
    type           VARCHAR(16)  NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    location_en    VARCHAR(200),
    location_zh    VARCHAR(200),
    location_ko    VARCHAR(200),
    description_en VARCHAR(2000),
    description_zh VARCHAR(2000),
    description_ko VARCHAR(2000),
    image          VARCHAR(500),
    source_name    VARCHAR(100),
    source_url     VARCHAR(500),
    is_official    BOOLEAN      NOT NULL,
    online_url     VARCHAR(500),
    map_url        VARCHAR(500)
);

-- 艺人档案（artists）；is_current 避开 PostgreSQL 保留字 CURRENT（存量库由 V2/V3 改名）
CREATE TABLE IF NOT EXISTS artists (
    id          VARCHAR(32)  PRIMARY KEY,
    name        VARCHAR(64)  NOT NULL,
    sub_name    VARCHAR(64),
    era_year    VARCHAR(4),
    era         VARCHAR(64),
    era_period  VARCHAR(32),
    accent      VARCHAR(16),
    accent_soft VARCHAR(16),
    hero_image  VARCHAR(500),
    source_tag  VARCHAR(32),
    intro_en    VARCHAR(2000),
    intro_zh    VARCHAR(2000),
    intro_ko    VARCHAR(2000),
    is_current  BOOLEAN      NOT NULL
);

-- 回归专题（comebacks）
CREATE TABLE IF NOT EXISTS comebacks (
    id               VARCHAR(32) PRIMARY KEY,
    artist_id        VARCHAR(32) NOT NULL,
    title            VARCHAR(64) NOT NULL,
    tagline_en       VARCHAR(64),
    tagline_zh       VARCHAR(64),
    tagline_ko       VARCHAR(64),
    release_date     VARCHAR(10) NOT NULL,
    release_time     VARCHAR(5)  NOT NULL,
    release_timezone VARCHAR(8)  NOT NULL
);

-- 回归时间线节点（comeback_stages，一对多）；comeback_id 类型匹配 comebacks.id（VARCHAR 主键）
CREATE TABLE IF NOT EXISTS comeback_stages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comeback_id VARCHAR(32) NOT NULL,
    stage_id    VARCHAR(32) NOT NULL,
    sort_order  INTEGER     NOT NULL,
    event_ids   VARCHAR(500),
    CONSTRAINT fk_comeback_stages_comeback FOREIGN KEY (comeback_id)
        REFERENCES comebacks (id) ON DELETE CASCADE
);

-- 教程板块（tutorials）；嵌套结构以 JSON 文本存 TEXT
CREATE TABLE IF NOT EXISTS tutorials (
    id            VARCHAR(32) PRIMARY KEY,
    status        VARCHAR(16) NOT NULL,
    title         VARCHAR(64) NOT NULL,
    tagline       VARCHAR(128),
    sections_json TEXT NOT NULL,
    notes_json    TEXT,
    no_count_json TEXT
);

-- 元数据（meta）
CREATE TABLE IF NOT EXISTS meta (
    meta_key   VARCHAR(32) PRIMARY KEY,
    meta_value TEXT NOT NULL
);

-- 用户（users，当前为管理后台账号）
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64),
    password_hash VARCHAR(300),
    role          VARCHAR(16) NOT NULL,
    created_at    BIGINT      NOT NULL,
    last_login_at BIGINT
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username);

-- 用户设备（user_devices，匿名设备锚点）
CREATE TABLE IF NOT EXISTS user_devices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id      VARCHAR(64) NOT NULL,
    user_id        BIGINT,
    platform       VARCHAR(16),
    created_at     BIGINT NOT NULL,
    last_active_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_devices_device_id ON user_devices (device_id);

-- 推送订阅（push_subscriptions，Web Push 投递地址）
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(64)  NOT NULL,
    endpoint   VARCHAR(500) NOT NULL,
    p256dh     VARCHAR(128) NOT NULL,
    auth       VARCHAR(64)  NOT NULL,
    created_at BIGINT       NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_push_subs_endpoint ON push_subscriptions (endpoint);
CREATE INDEX IF NOT EXISTS idx_push_subs_device ON push_subscriptions (device_id);

-- 推送调度（push_schedules，Fan-out 调度单元）
CREATE TABLE IF NOT EXISTS push_schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       VARCHAR(32) NOT NULL,
    offset_minutes INTEGER     NOT NULL,
    trigger_at     BIGINT      NOT NULL,
    status         VARCHAR(16) NOT NULL,
    processed_at   BIGINT,
    attempt_id     BIGINT,
    retry_count    INTEGER     NOT NULL,
    next_retry_at  BIGINT,
    finished_at    BIGINT,
    created_at     BIGINT      NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_schedule_event_offset ON push_schedules (event_id, offset_minutes);
CREATE INDEX IF NOT EXISTS idx_schedules_status_trigger ON push_schedules (status, trigger_at);
CREATE INDEX IF NOT EXISTS idx_schedules_status_retry ON push_schedules (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_schedules_status_processed ON push_schedules (status, processed_at);

-- 推送任务（push_tasks，Fan-out 执行单元）
CREATE TABLE IF NOT EXISTS push_tasks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id      VARCHAR(64)  NOT NULL,
    event_id       VARCHAR(32)  NOT NULL,
    schedule_id    BIGINT,
    offset_minutes INTEGER      NOT NULL,
    trigger_at     BIGINT       NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    processed_at   BIGINT,
    attempt_id     BIGINT,
    retry_count    INTEGER      NOT NULL,
    next_retry_at  BIGINT,
    sent_at        BIGINT,
    error_message  VARCHAR(500),
    created_at     BIGINT       NOT NULL
);
-- 同一设备在同一调度下只能存在一个任务（syncReminders 全量替换的并发兜底，防止重复推送）
CREATE UNIQUE INDEX IF NOT EXISTS uk_push_tasks_schedule_device ON push_tasks (schedule_id, device_id);
CREATE INDEX IF NOT EXISTS idx_push_tasks_status_trigger ON push_tasks (status, trigger_at);
CREATE INDEX IF NOT EXISTS idx_push_tasks_status_retry ON push_tasks (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_push_tasks_device ON push_tasks (device_id);
CREATE INDEX IF NOT EXISTS idx_push_tasks_schedule ON push_tasks (schedule_id);

-- 投递日志（push_delivery_logs，每次发送一条）
CREATE TABLE IF NOT EXISTS push_delivery_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id       BIGINT,
    device_id     VARCHAR(64)  NOT NULL,
    endpoint      VARCHAR(200) NOT NULL,
    sent_at       BIGINT       NOT NULL,
    http_status   INTEGER      NOT NULL,
    result        VARCHAR(16)  NOT NULL,
    error_message VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_delivery_sent_at ON push_delivery_logs (sent_at);
CREATE INDEX IF NOT EXISTS idx_delivery_task ON push_delivery_logs (task_id);
CREATE INDEX IF NOT EXISTS idx_delivery_result_sent ON push_delivery_logs (result, sent_at);
